---
image_one: c2900-IMAGE-ONE.SPA.154-3.M3.bin
image_two: c2900-IMAGE-TWO.SPA.151-4.M1.bin
platform: cisco_ios_ssh
ansible_connection: local
ansible_user: vagrant
provider:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_password }}"
  transport: cli

