---
- name: update gig ip address
  gather_facts: no
  hosts: routers
  tasks:

    - name: apply template config
      ios_template:
        provider: "{{ provider }}"
        src: update_gig_ip.j2
      register: output
    - debug: var=output
