---
- name: Show Version
  hosts: routers
  tasks:
    - ios_command:
        provider: "{{ cli }}"
        commands:
          - show version
      register: output
    - debug: msg="{{ output.stdout_lines }}"
