---
- name: Show Version
  gather_facts: no
  hosts: routers
  tasks:
    - ios_command:
        provider: "{{ cli }}"
        commands:
          - show run
      register: output
    - debug: var=output.stdout_lines

