---
- name: Show Run To File
  gather_facts: no
  hosts: test_routers
  tasks:

    - name: execute show run command
      ios_command:
        provider: "{{ cli }}"
        commands:
          - show run
      register: output

    - name: write output to file
      template:
        src: output.conf.j2
        dest: /home/vagrant/shared/output/{{ ansible_host }}.conf

