---
- name: Show Version
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - ios_command:
        provider: "{{ cli }}"
        commands:
          - show version
      register: output
    - debug: msg="Output - "{{ output.stdout_lines }}""
